=== destrodevianne/reb_h5_storm/rebellion_h5_realm/dist/gameserver/config/CustomDroplist.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="list" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="reward">
    <xs:complexType>
      <xs:attribute name="item_id" type="xs:string" />
      <xs:attribute name="min" type="xs:string" />
      <xs:attribute name="max" type="xs:string" />
      <xs:attribute name="chance" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="list" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="reward" />
        <xs:element name="npc">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="rewardlist" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="reward" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element name="group" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="reward" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                        <xs:attribute name="chance" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="minLevel" type="xs:string" />
            <xs:attribute name="maxLevel" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== destrodevianne/reb_h5_storm/rebellion_h5_realm/dist/gameserver/config/CustomDroplist.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CustomDroplist.xsd">
	<npc minLevel="1" maxLevel="10">
		<rewardlist type="RATED_GROUPED">
			<group chance="70.0">
				<reward item_id="57" min="99" max="140" chance="100.0000" />	<!--Adena-->
			</group>
			<group chance="0.0535">
				<reward item_id="271" min="1" max="1" chance="100.0000" />	<!--Hunting Bow-->
			</group>
			<group chance="11.6767">
				<reward item_id="1866" min="1" max="1" chance="21.1765" />	<!--Suede-->
				<reward item_id="1871" min="1" max="1" chance="31.7647" />	<!--Charcoal-->
				<reward item_id="1799" min="1" max="1" chance="47.0588" />	<!--Recipe: Leather Gloves-->
			</group>
		</rewardlist>
		<rewardlist type="SWEEP">
			<reward item_id="1833" min="1" max="1" chance="50.2269" />	<!--Bandage-->
			<reward item_id="1866" min="1" max="1" chance="12.5567" />	<!--Suede-->
			<reward item_id="1792" min="1" max="1" chance="1.3849" />	<!--Recipe: Short Spear-->
		</rewardlist>
	</npc>
	<npc minLevel="11" maxLevel="20">
		<rewardlist type="RATED_GROUPED">
			<group chance="70.0">
				<reward item_id="57" min="99" max="140" chance="100.0000" />	<!--Adena-->
			</group>
			<group chance="0.0535">
				<reward item_id="271" min="1" max="1" chance="100.0000" />	<!--Hunting Bow-->
			</group>
			<group chance="11.6767">
				<reward item_id="1866" min="1" max="1" chance="21.1765" />	<!--Suede-->
				<reward item_id="1871" min="1" max="1" chance="31.7647" />	<!--Charcoal-->
				<reward item_id="1799" min="1" max="1" chance="47.0588" />	<!--Recipe: Leather Gloves-->
			</group>
		</rewardlist>
		<rewardlist type="SWEEP">
			<reward item_id="1833" min="1" max="1" chance="50.2269" />	<!--Bandage-->
			<reward item_id="1866" min="1" max="1" chance="12.5567" />	<!--Suede-->
			<reward item_id="1792" min="1" max="1" chance="1.3849" />	<!--Recipe: Short Spear-->
		</rewardlist>
	</npc>
</list>
