=== destrodevianne/reb_h5_storm/rebellion_h5_realm/dist/gameserver/config/enchant_items.dtd
<!ELEMENT list (enchant_scroll | default)*>
<!ELEMENT default (#PCDATA)>
<!ATTLIST default
	chance CDATA #REQUIRED
	magic_chance CDATA #IMPLIED
	max_enchant CDATA #REQUIRED
	succ_eff_ench_min CDATA #IMPLIED
	succ_eff_ench_max CDATA #IMPLIED
	show_fail_effect CDATA #IMPLIED
	safe_level CDATA #IMPLIED
	safe_level_full_armor CDATA #IMPLIED>
<!ELEMENT enchant_scroll (item_list|grade_list|chance_per_level)*>
<!ATTLIST enchant_scroll
	id CDATA #REQUIRED
	chance CDATA #IMPLIED
	magic_chance CDATA #IMPLIED
	succ_eff_ench_min CDATA #IMPLIED
	succ_eff_ench_max CDATA #IMPLIED
	show_fail_effect CDATA #IMPLIED
	on_fail CDATA #REQUIRED
	max_enchant CDATA #IMPLIED
	type CDATA #IMPLIED
	grade CDATA #IMPLIED
	safe_level CDATA #IMPLIED
	safe_level_full_armor CDATA #IMPLIED>
<!ELEMENT grade_list (grade)*>
<!ELEMENT item_list (item)*>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
	id CDATA #REQUIRED>
<!ELEMENT grade (#PCDATA)>
<!ATTLIST grade
	id CDATA #REQUIRED>
<!ELEMENT chance_per_level (chance)*>
<!ELEMENT chance (#PCDATA)>
<!ATTLIST chance
	level CDATA #REQUIRED
	chance CDATA #REQUIRED>

=== destrodevianne/reb_h5_storm/rebellion_h5_realm/dist/gameserver/config/enchant_items.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "enchant_items.dtd">
<list>
	<!-- default chance will work for missing scroll in this list. -->
	<default chance="45" magic_chance="44" max_enchant="16" safe_level="3" safe_level_full_armor="4" succ_eff_ench_min="6" succ_eff_ench_max="15" />

	<!--####### Common Enchant Scrolls ####### -->
	<!--Scroll: Enchant Weapon (D-Grade)-->
	<enchant_scroll id="955" on_fail="CRYSTALS" type="WEAPON" succ_eff_ench_min="7" grade="D" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="60" />
			<chance level="5" chance="55" />
			<chance level="6" chance="52" />
			<chance level="7" chance="50" />
			<chance level="8" chance="48" />
			<chance level="9" chance="40" />
			<chance level="10" chance="38" />
			<chance level="11" chance="35" />
			<chance level="12" chance="33" />
			<chance level="13" chance="30" />
			<chance level="14" chance="25" />
			<chance level="15" chance="15" />
			<chance level="16" chance="10" />
		</chance_per_level>
	</enchant_scroll>

	<!--Scroll: Enchant Armor (D-Grade)-->
	<enchant_scroll id="956" on_fail="CRYSTALS" type="ARMOR" grade="D" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="60" />
			<chance level="5" chance="55" />
			<chance level="6" chance="52" />
			<chance level="7" chance="50" />
			<chance level="8" chance="48" />
			<chance level="9" chance="40" />
			<chance level="10" chance="38" />
			<chance level="11" chance="35" />
			<chance level="12" chance="33" />
			<chance level="13" chance="30" />
			<chance level="14" chance="25" />
			<chance level="15" chance="15" />
			<chance level="16" chance="10" />
		</chance_per_level>
	</enchant_scroll>

	<!--Scroll: Enchant Weapon (C-Grade)-->
	<enchant_scroll id="951" on_fail="CRYSTALS" type="WEAPON" succ_eff_ench_min="7" grade="C" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="60" />
			<chance level="5" chance="55" />
			<chance level="6" chance="52" />
			<chance level="7" chance="50" />
			<chance level="8" chance="48" />
			<chance level="9" chance="40" />
			<chance level="10" chance="38" />
			<chance level="11" chance="35" />
			<chance level="12" chance="33" />
			<chance level="13" chance="30" />
			<chance level="14" chance="25" />
			<chance level="15" chance="15" />
			<chance level="16" chance="10" />
		</chance_per_level>
	</enchant_scroll>
	
	<!--Scroll: Enchant Armor (C-Grade)-->
	<enchant_scroll id="952" on_fail="CRYSTALS" type="ARMOR" grade="C" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="60" />
			<chance level="5" chance="55" />
			<chance level="6" chance="52" />
			<chance level="7" chance="50" />
			<chance level="8" chance="48" />
			<chance level="9" chance="40" />
			<chance level="10" chance="38" />
			<chance level="11" chance="35" />
			<chance level="12" chance="33" />
			<chance level="13" chance="30" />
			<chance level="14" chance="25" />
			<chance level="15" chance="15" />
			<chance level="16" chance="10" />
		</chance_per_level>
	</enchant_scroll>
	
	<!--Scroll: Enchant Weapon (B-Grade)-->
	<enchant_scroll id="947" on_fail="CRYSTALS" type="WEAPON" succ_eff_ench_min="7" grade="B" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="60" />
			<chance level="5" chance="55" />
			<chance level="6" chance="52" />
			<chance level="7" chance="50" />
			<chance level="8" chance="48" />
			<chance level="9" chance="40" />
			<chance level="10" chance="38" />
			<chance level="11" chance="35" />
			<chance level="12" chance="33" />
			<chance level="13" chance="30" />
			<chance level="14" chance="25" />
			<chance level="15" chance="15" />
			<chance level="16" chance="10" />
		</chance_per_level>
	</enchant_scroll>
	
	<!--Scroll: Enchant Armor (B-Grade)-->
	<enchant_scroll id="948" on_fail="CRYSTALS" type="ARMOR" grade="B" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="60" />
			<chance level="5" chance="55" />
			<chance level="6" chance="52" />
			<chance level="7" chance="50" />
			<chance level="8" chance="48" />
			<chance level="9" chance="40" />
			<chance level="10" chance="38" />
			<chance level="11" chance="35" />
			<chance level="12" chance="33" />
			<chance level="13" chance="30" />
			<chance level="14" chance="25" />
			<chance level="15" chance="15" />
			<chance level="16" chance="10" />
		</chance_per_level>
	</enchant_scroll>
	
	<!--Scroll: Enchant Weapon (A-Grade)-->
	<enchant_scroll id="729" on_fail="CRYSTALS" type="WEAPON" succ_eff_ench_min="7" grade="A" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="60" />
			<chance level="5" chance="55" />
			<chance level="6" chance="52" />
			<chance level="7" chance="50" />
			<chance level="8" chance="48" />
			<chance level="9" chance="40" />
			<chance level="10" chance="38" />
			<chance level="11" chance="35" />
			<chance level="12" chance="33" />
			<chance level="13" chance="30" />
			<chance level="14" chance="25" />
			<chance level="15" chance="15" />
			<chance level="16" chance="10" />
		</chance_per_level>
	</enchant_scroll>
	
	<!--Scroll: Enchant Armor (A-Grade)-->
	<enchant_scroll id="730" on_fail="CRYSTALS" type="ARMOR" grade="A" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="60" />
			<chance level="5" chance="55" />
			<chance level="6" chance="52" />
			<chance level="7" chance="50" />
			<chance level="8" chance="48" />
			<chance level="9" chance="40" />
			<chance level="10" chance="38" />
			<chance level="11" chance="35" />
			<chance level="12" chance="33" />
			<chance level="13" chance="30" />
			<chance level="14" chance="25" />
			<chance level="15" chance="15" />
			<chance level="16" chance="10" />
		</chance_per_level>
	</enchant_scroll>
	
	<!--Scroll: Enchant Weapon (S-Grade)-->
	<enchant_scroll id="959" on_fail="CRYSTALS" type="WEAPON" succ_eff_ench_min="7" grade="S" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="60" />
			<chance level="5" chance="55" />
			<chance level="6" chance="52" />
			<chance level="7" chance="50" />
			<chance level="8" chance="48" />
			<chance level="9" chance="40" />
			<chance level="10" chance="38" />
			<chance level="11" chance="35" />
			<chance level="12" chance="33" />
			<chance level="13" chance="30" />
			<chance level="14" chance="25" />
			<chance level="15" chance="15" />
			<chance level="16" chance="10" />
		</chance_per_level>
	</enchant_scroll>
	
	<!--Scroll: Enchant Armor (S-Grade)-->
	<enchant_scroll id="960" on_fail="CRYSTALS" type="ARMOR" grade="S" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="60" />
			<chance level="5" chance="55" />
			<chance level="6" chance="52" />
			<chance level="7" chance="50" />
			<chance level="8" chance="48" />
			<chance level="9" chance="40" />
			<chance level="10" chance="38" />
			<chance level="11" chance="35" />
			<chance level="12" chance="33" />
			<chance level="13" chance="30" />
			<chance level="14" chance="25" />
			<chance level="15" chance="15" />
			<chance level="16" chance="10" />
		</chance_per_level>
	</enchant_scroll>
	
	<!--Crystal Enchant Scrolls-->
	<!--Crystal Scroll: Enchant Weapon (D-Grade)-->
	<enchant_scroll id="957" on_fail="CRYSTALS" type="WEAPON" succ_eff_ench_min="7" grade="D" chance="50" max_enchant="16"/>

	<!--Crystal Scroll: Enchant Armor (D-Grade)-->
	<enchant_scroll id="958" on_fail="CRYSTALS" type="ARMOR" grade="D" chance="50" max_enchant="16"/>

	<!--Crystal Scroll: Enchant Weapon (C-Grade)-->
	<enchant_scroll id="953" on_fail="CRYSTALS" type="WEAPON" succ_eff_ench_min="7" grade="C" chance="50" max_enchant="16"/>

	<!--Crystal Scroll: Enchant Armor (C-Grade)-->
	<enchant_scroll id="954" on_fail="CRYSTALS" type="ARMOR" grade="C" chance="50" max_enchant="16"/>

	<!--Crystal Scroll: Enchant Weapon (B-Grade)-->
	<enchant_scroll id="949" on_fail="CRYSTALS" type="WEAPON" succ_eff_ench_min="7" grade="B" chance="50" max_enchant="16"/>

	<!--Crystal Scroll: Enchant Armor (B-Grade)-->
	<enchant_scroll id="950" on_fail="CRYSTALS" type="ARMOR" grade="B" chance="50" max_enchant="16"/>

	<!--Crystal Scroll: Enchant Weapon (A-Grade)-->
	<enchant_scroll id="731" on_fail="CRYSTALS" type="WEAPON" succ_eff_ench_min="7" grade="A" chance="50" max_enchant="16"/>

	<!--Crystal Scroll: Enchant Armor (A-Grade)-->
	<enchant_scroll id="732" on_fail="CRYSTALS" type="ARMOR" grade="A" chance="50" max_enchant="16"/>

	<!--Crystal Scroll: Enchant Weapon (S-Grade)-->
	<enchant_scroll id="961" on_fail="CRYSTALS" type="WEAPON" succ_eff_ench_min="7" grade="S" chance="50" max_enchant="16"/>

	<!--Crystal Scroll: Enchant Armor (S-Grade)-->
	<enchant_scroll id="962" on_fail="CRYSTALS" type="ARMOR" grade="S" chance="50" max_enchant="16"/>

	<!--Blessed Enchant Scrolls-->
	<!--Blessed Scroll: Enchant Weapon (D-Grade)-->
	<enchant_scroll id="6575" on_fail="DROP_ENCHANT" type="WEAPON" succ_eff_ench_min="7" grade="D" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="75" />
			<chance level="5" chance="66" />
			<chance level="6" chance="66" />
			<chance level="7" chance="50" />
			<chance level="8" chance="50" />
			<chance level="9" chance="50" />
			<chance level="10" chance="45" />
			<chance level="11" chance="40" />
			<chance level="12" chance="30" />
			<chance level="13" chance="25" />
			<chance level="14" chance="20" />
			<chance level="15" chance="15" />
			<chance level="16" chance="10" />
		</chance_per_level>
	</enchant_scroll>
	
	<!--Blessed Scroll: Enchant Armor (D-Grade)-->
	<enchant_scroll id="6576" on_fail="DROP_ENCHANT" type="ARMOR" grade="D" chance="50" max_enchant="16">
		<chance_per_level>
			<chance level="4" chance="75" />
			<chance level="5" chance="66" />
			<chance level="6" chance="66" />
			<chance level="7" chance="50" />
			<chance level="8" chance="50" />
